name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
  deploy:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - run: sudo docker stop nextapp || true
      - run: sudo docker build . -t nextapp
      - run: sudo docker run -d --rm --name=nextapp nextapp
